### ISSUE TITLE
Tutorial: tracing code

### ISSUE THREAD

**Issue by Guo-KeCheng** [AY2223S2-CS2103-F10-1/tp#11]
![image](https://user-images.githubusercontent.com/96603198/220050206-92d317b7-bd7f-4d3d-a72f-559fa3a65293.png)
Running `edit 1 n/アリス ユー` with breakpoint set to `logic.execute(commandText)`
</br>
</br>

![image](https://user-images.githubusercontent.com/96603198/220054327-8e94448f-1e7d-400d-b6eb-df9e8c9f3b81.png)
Error is thrown when `ParserUtil.parseName(argMultimap.getValue(PREFIX_NAME).get())`
</br>
</br>

![image](https://user-images.githubusercontent.com/96603198/220054466-9d81e0be-fb8c-404f-8c5b-b15ee31eaf75.png)
Upon further investigation, the name is not valid, hence, a ParseException is thrown.
</br>
</br>

**Comment by SPWwj** [comment]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/30100720/220506230-5df15ef4-42fa-49d4-892e-24813ddeec56.png">

Running `edit 1 t/one t/two t/three t/one` with breakpoint set to logic.execute(commandText)

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/30100720/220506729-763f7040-d1b1-436e-908f-d98c46442ac6.png">

Step into the switch statement

<img width="898" alt="image" src="https://user-images.githubusercontent.com/30100720/220507029-535691ab-1316-4d91-aa66-09f9990d8275.png">

`edit `arguments is successfully captured.

**Comment by kayyenl** [comment]
Hello friends :D here is my attempt at the code tracing..

![image](https://user-images.githubusercontent.com/99934242/221114911-1d33a161-7dec-419d-8055-c0fe7dc29aaf.png)
^ Input at MainWindow (before going into the LogicManager class) after entering ```edit 1 n/アリス ユー```

![image](https://user-images.githubusercontent.com/99934242/221115241-36a49856-f319-47b8-ae88-6ad1ea2124d2.png)
^ in AddressBookParser class, still no exception being thrown and UserInput is successfully captured still

![image](https://user-images.githubusercontent.com/99934242/221115712-add839ed-41ea-4109-ab94-0470ba22d053.png)
^ parsing the (seemingly problematic) ```1 n/アリス ユー```, edit is successfully separated from this term.

![image](https://user-images.githubusercontent.com/99934242/221115939-05db12f7-df5b-46dc-b67e-4e39666d1b06.png)
^ index ```1``` captured by the ```index = ParserUtil.parseIndex(argMultimap.getPreamble());``` command. 

![image](https://user-images.githubusercontent.com/99934242/221116124-96b57983-bce5-40b5-bde3-48897a107b7e.png)
^ Scanning the ```n/アリス ユー``` with this line... 
```editPersonDescriptor.setName(ParserUtil.parseName(argMultimap.getValue(PREFIX_NAME).get()));``` is being invoked, since ```argMultimap.getValue(PREFIX_NAME).isPresent()``` conditional is being satisfied.

![image](https://user-images.githubusercontent.com/99934242/221116528-61764ca5-13c9-4858-96dc-e2a9c01f58f4.png)
^ just when the method above has been invoked, invalid command spotted! ParseException thrown.

This is the overview for a single case, when ```edit 1 n/アリス ユー``` is being entered.
